image: pfeilda/continousintegration:php7-1-composer1-7-2

before_script:
  - apk add --no-cache $PHPIZE_DEPS && pecl install xdebug-2.6.0 && docker-php-ext-enable xdebug
  - git config --global url."https://gitlab+deploy-token-4:${ServiceAuthenticatorDeployToken}@git.api-studio.de/pfeilda/serviceproviderAuthenticator.git".insteadOf git@git.api-studio.de:pfeilda/serviceproviderAuthenticator.git
  - composer install -o

test:
  stage: build
  script:
    - vendor/bin/phpspec run --no-code-generation --no-code-coverage -n
  artifacts:
    paths:
      - coverage